version: 2.1
jobs:
  build:
    docker:
      - image:  cimg/openjdk:11.0.16
    working_directory: ~/repo

    steps:
      - checkout
      - run: ./gradlew build
      - run:
          name: Sonarqube analysis
          command: ./gradlew sonarqube

workflows:
  version: 2
  build:
    jobs:
      - build